language: en

# Gui icons
# For each icon, you can use
# - a simple item
# - a playerHead with a texture
gui:
  category:
    emptyIcon:
      type: COARSE_DIRT
  borderIcon:
    type: GRAY_STAINED_GLASS_PANE
  previousIcon:
    type: PLAYER_HEAD
    textureId: 8652e2b936ca8026bd28651d7c9f2819d2e923697734d18dfdb13550f8fdad5f
  nextIcon:
    type: PLAYER_HEAD
    textureId: 2a3b8f681daad8bf436cae8da3fe8131f62a162ab81af639c3e0644aa6abac2f
  infoIcon:
    display: true
    type: PLAYER_HEAD
    textureId: 5db532b5cced46b4b535ece16eced7bbc5cac55594d61e8b8f8eac4299c9fc
  backIcon:
    type: PLAYER_HEAD
    textureId: 865426a33df58b465f0601dd8b9bec3690b2193d1f9503c2caab78f6c2438
  closeIcon:
    type: PLAYER_HEAD
    textureId: 5a6787ba32564e7c2f3a0ce64498ecbb23b89845e5a66b5cec7736f729ed37